---
title: "Practical R Exercises in Swirl"
output: rmarkdown::github_document
---
# 5: Missing Values 

  |                                                                                                                                                                                                      |   0%  

| Missing values play an important role in statistics and data analysis. Often, missing values must not be ignored, but rather they should be carefully studied to see if there's an underlying pattern or
| cause for their missingness.

...

  |==========                                                                                                                                                                                            |   5%  
| In R, NA is used to represent any value that is 'not available' or 'missing' (in the statistical sense). In this lesson, we'll explore missing values further.

...

  |====================                                                                                                                                                                                  |  10%  
| Any operation involving NA generally yields NA as the result. To illustrate, let's create a vector c(44, NA, 5, NA) and assign it to a variable x.

`> x <- c(44, NA, 5, NA)`

| All that hard work is paying off!

  |==============================                                                                                                                                                                        |  15%  
| Now, let's multiply x by 3.

`> x * 3`  
`[1] 132  NA  15  NA`

| You're the best!

  |========================================                                                                                                                                                              |  20%  
| Notice that the elements of the resulting vector that correspond with the NA values in x are also NA.

...

  |==================================================                                                                                                                                                    |  25%  
| To make things a little more interesting, lets create a vector containing 1000 draws from a standard normal distribution with y <- rnorm(1000).

**`> y <- rnorm(1000)`**

| You are doing so well!

  |===========================================================                                                                                                                                           |  30%  
| Next, let's create a vector containing 1000 NAs with z <- rep(NA, 1000).

`> z <- rep(NA, 1000)`

| Keep up the great work!

  |=====================================================================                                                                                                                                 |  35%  
| Finally, let's select 100 elements at random from these 2000 values (combining y and z) such that we don't know how many NAs we'll wind up with or what positions they'll occupy in our final vector --
| my_data <- sample(c(y, z), 100).

**`> my_data <- sample(c(y, z), 100)`**

| Keep working like that and you'll get there!

  |===============================================================================                                                                                                                       |  40%  
| Let's first ask the question of where our NAs are located in our data. The is.na() function tells us whether each element of a vector is NA. Call is.na() on my_data and assign the result to my_na.

`> my_na <- is.na(my_data)`

| Great job!

  |=========================================================================================                                                                                                             |  45%  
| Now, print my_na to see what you came up with.

`> my_na`  
`  [1]  TRUE FALSE  TRUE  TRUE FALSE FALSE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE  TRUE  TRUE FALSE  TRUE FALSE FALSE  TRUE FALSE FALSE  TRUE  TRUE  TRUE`  
` [34]  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE FALSE FALSE  TRUE FALSE  TRUE FALSE FALSE FALSE  TRUE  TRUE FALSE  TRUE  TRUE FALSE FALSE  TRUE FALSE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE`  
` [67] FALSE  TRUE FALSE  TRUE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE FALSE FALSE  TRUE  TRUE FALSE FALSE  TRUE FALSE  TRUE  TRUE FALSE  TRUE  TRUE FALSE FALSE FALSE  TRUE FALSE`  
`[100] FALSE`

| You are really on a roll!

  |===================================================================================================                                                                                                   |  50%  
| Everywhere you see a TRUE, you know the corresponding element of my_data is NA. Likewise, everywhere you see a FALSE, you know the corresponding element of my_data is one of our random draws from the
| standard normal distribution.

...

  |=============================================================================================================                                                                                         |  55%  
| In our previous discussion of logical operators, we introduced the `==` operator as a method of testing for equality between two objects. So, you might think the expression my_data == NA yields the same
| results as is.na(). Give it a try.

`> my_data == NA`  
`  [1] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA`  
` [68] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA`  

| All that practice is paying off!

  |=======================================================================================================================                                                                               |  60%  
| The reason you got a vector of all NAs is that NA is not really a value, but just a placeholder for a quantity that is not available. Therefore the logical expression is incomplete and R has no choice but
| to return a vector of the same length as my_data that contains all NAs.

...

  |=================================================================================================================================                                                                     |  65%  
| Don't worry if that's a little confusing. The key takeaway is to be cautious when using logical expressions anytime NAs might creep in, since a single NA value can derail the entire thing.

...

  |===========================================================================================================================================                                                           |  70%  
| So, back to the task at hand. Now that we have a vector, my_na, that has a TRUE for every NA and FALSE for every numeric value, we can compute the total number of NAs in our data.

...

  |====================================================================================================================================================                                                  |  75%  
| The trick is to recognize that underneath the surface, R represents TRUE as the number 1 and FALSE as the number 0. Therefore, if we take the sum of a bunch of TRUEs and FALSEs, we get the total number of
| TRUEs.

...

  |==============================================================================================================================================================                                        |  80%  
| Let's give that a try here. Call the sum() function on my_na to count the total number of TRUEs in my_na, and thus the total number of NAs in my_data. Don't assign the result to a new variable.

`> sum(my_na)`  
`[1] 47`

| That's correct!

  |========================================================================================================================================================================                              |  85%  
| Pretty cool, huh? Finally, let's take a look at the data to convince ourselves that everything 'adds up'. Print my_data to the console.

`> my_data`  
`  [1]           NA  1.266353156           NA           NA  0.347349985  0.374583985 -0.212860097           NA  0.935878884           NA           NA           NA           NA           NA  0.384943676`  
` [16]  1.212686031  0.615084775 -0.682011636           NA  0.986358782  0.869776324           NA           NA -0.537595550           NA  0.503436085 -1.400486113           NA  1.795180676  0.339183264`  
` [31]           NA           NA           NA           NA           NA           NA           NA  0.503784199           NA -0.776962230           NA           NA  0.008687269 -0.551526682           NA`  
` [46] -0.473798637           NA -0.758461623  0.681697774 -0.190924080           NA           NA -0.229968032           NA           NA -0.880510789 -0.961253644           NA -0.542149599           NA`  
` [61]           NA           NA  1.005762329 -1.393603145  0.330159575  0.123630542  0.263463160           NA  0.428755066           NA  0.276654402  0.121007049           NA  0.472119263  0.951038640`  
` [76]  1.528600236  1.136787869           NA  0.540370913           NA  0.233536747  1.230492155  1.107991053           NA           NA  0.473902689 -0.111786379           NA  0.040911316           NA`  
` [91]           NA  0.359944706           NA           NA  0.683843190  0.413339196  1.581541594           NA -0.747459673 -0.465558328`  

| That's the answer I was looking for.

  |==================================================================================================================================================================================                    |  90%  
| Now that we've got NAs down pat, let's look at a second type of missing value -- NaN, which stands for 'not a number'. To generate NaN, try dividing (using a forward slash) 0 by 0 now.

`> 0 / 0`  
`[1] NaN`

| You got it!

  |============================================================================================================================================================================================          |  95%  
| Let's do one more, just for fun. In R, Inf stands for infinity. What happens if you subtract Inf from Inf?

`> Inf - Inf`  
`[1] NaN`

| You are really on a roll!

  |======================================================================================================================================================================================================| 100%  
| Would you like to receive credit for completing this course on Coursera.org?

1: Yes
2: No

Selection: 